version: '2.1'

services:

  database:
    image: mongo:3.4.9
    container_name: test_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
    - 27017:27017
    healthcheck:
      test: timeout 1 bash -c 'echo > /dev/tcp/localhost/27017';
      interval: 10s
      timeout: 3s
      retries: 5
